#pragma once

#include <QMainWindow>
#include <QtSvg>
#include <QHBoxLayout>
#include <QVBoxLayout>
#include <QPushButton>
#include <QLineEdit>
#include <QString>
#include <QGraphicsView>
#include <QGraphicsScene>
#include <QWidget>
#include <initializer_list>
#include <utility>
#include <QVector>
#include <QMenu>
#include <QFileDialog>
#include <QPainter>
#include <QSvgRenderer>
#include <QPair>
#include <QColor>
